# Generated by Django 5.1.4 on 2025-02-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("Patient", "Patient"),
                    ("Doctor", "Doctor"),
                    ("Admin", "Admin"),
                    ("MasterAdmin", "Master Admin"),
                    ("Reception", "Receptionist"),
                    ("TestCentre", "Test Centre"),
                ],
                max_length=20,
            ),
        ),
    ]
