# Generated by Django 5.1.4 on 2025-02-13 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
