# Generated by Django 5.1.4 on 2025-02-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_users_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
    ]
