# Generated by Django 5.1.4 on 2025-02-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_users_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctors",
            name="address",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="specialization",
        ),
        migrations.RemoveField(
            model_name="doctors",
            name="user",
        ),
        migrations.AddField(
            model_name="doctors",
            name="achievements",
            field=models.TextField(default="No achievements added"),
        ),
        migrations.AddField(
            model_name="doctors",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.departments",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="education",
            field=models.TextField(default="No Education added"),
        ),
        migrations.AddField(
            model_name="doctors",
            name="expertise",
            field=models.TextField(default="No expertise added"),
        ),
        migrations.AddField(
            model_name="doctors",
            name="hospitals_worked",
            field=models.TextField(default="syncHealth"),
        ),
        migrations.AddField(
            model_name="doctors",
            name="name",
            field=models.CharField(default="Doctor's Name", max_length=100),
        ),
        migrations.AddField(
            model_name="doctors",
            name="nmc_registration",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="doctors",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
    ]
