# Generated by Django 5.1.4 on 2025-02-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_doctors_address_remove_doctors_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
    ]
