# Generated by Django 5.1.4 on 2025-02-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_departments_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.departments",
                to_field="name",
            ),
        ),
    ]
