# Generated by Django 5.1.4 on 2025-02-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_departments_name_alter_doctors_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patients",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="user",
        ),
        migrations.AddField(
            model_name="patients",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patients",
            name="assigned_doctors",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patients",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="health_issues",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="patients",
            name="name",
            field=models.CharField(default="Patients Name", max_length=100),
        ),
        migrations.AddField(
            model_name="patients",
            name="patient_no",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="address",
            field=models.TextField(default="Patient's addredd"),
        ),
        migrations.AlterField(
            model_name="patients",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
