# Generated by Django 5.1.4 on 2025-02-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_patients_phone_remove_patients_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
