# Generated by Django 5.1.4 on 2025-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_doctors_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="department",
            field=models.TextField(default="No Departments added"),
        ),
    ]
