# Generated by Django 5.1.4 on 2025-02-22 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_doctors_department"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HealthTestBookings",
            new_name="HealthPackageBookings",
        ),
        migrations.RenameModel(
            old_name="HealthTests",
            new_name="HealthPackages",
        ),
    ]
