# Generated by Django 5.1.4 on 2025-02-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_healthpackagebookings_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthpackages",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
    ]
