# Generated by Django 5.1.4 on 2025-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_testcentre_testbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcentre",
            name="testcentre_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="testcentre_pics/"
            ),
        ),
    ]
