# Generated by Django 5.1.4 on 2025-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_testcentre_testcentre_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcentre",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
