# Generated by Django 5.1.4 on 2025-03-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_testcentre_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctoravailability",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="appointments",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointments",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="break_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="break_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="working_day_type",
            field=models.CharField(
                choices=[
                    ("Full", "Full Day"),
                    ("Half", "Half Day"),
                    ("Leave", "Leave"),
                ],
                default="Full",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospitalbranches",
                to_field="branch_code",
            ),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.doctoravailability",
            ),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patients",
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.users",
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
