# Generated by Django 5.1.4 on 2025-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_doctoravailability_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailability",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
