# Generated by Django 5.1.4 on 2025-03-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_doctoravailability_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoravailability",
            name="working_day_type",
            field=models.CharField(
                choices=[
                    ("Full", "Full Day"),
                    ("Half_Morning", "Half Morning"),
                    ("Half_Evening", "Half Evening"),
                    ("Leave", "Leave"),
                ],
                default="Full",
                max_length=20,
            ),
        ),
    ]
