# Generated by Django 5.1.4 on 2025-03-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_doctoravailability_working_day_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailability",
            name="emergency_available",
            field=models.BooleanField(default=False),
        ),
    ]
