# Generated by Django 5.1.4 on 2025-03-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_doctoravailability_emergency_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
    ]
