# Generated by Django 5.1.4 on 2025-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_appointments_is_emergency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="doctor",
            field=models.CharField(default="Doctor's Email", max_length=100),
        ),
    ]
