# Generated by Django 5.1.4 on 2025-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_appointments_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="branch",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="patient",
            field=models.CharField(default="Patient's Email", max_length=100),
        ),
    ]
