# Generated by Django 5.1.4 on 2025-03-14 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_appointments_branch_alter_appointments_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="appointments",
            name="start_time",
        ),
    ]
