# Generated by Django 5.1.4 on 2025-03-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_appointments_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="doctor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patients",
                to_field="email",
            ),
        ),
    ]
