# Generated by Django 5.1.4 on 2025-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_reviews_doctor_alter_reviews_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="rating_counts",
            field=models.IntegerField(default=0),
        ),
    ]
