# Generated by Django 5.1.4 on 2025-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_doctors_rating_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="rating",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
