# Generated by Django 5.1.4 on 2025-03-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_doctors_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptions",
            old_name="blood_pressure",
            new_name="pressure_diastolic",
        ),
        migrations.AddField(
            model_name="prescriptions",
            name="pressure_systolic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="prescriptions",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.doctors",
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptions",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patients",
                to_field="email",
            ),
        ),
    ]
