# Generated by Django 5.1.4 on 2025-03-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0028_rename_blood_pressure_prescriptions_pressure_diastolic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testresults",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="health_test_reports/"
            ),
        ),
    ]
