# Generated by Django 5.1.4 on 2025-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_testresults_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptions",
            name="doctor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="prescriptions",
            name="patient",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
