# Generated by Django 5.1.4 on 2025-04-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_prescriptions_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptions",
            name="appointment_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.appointments",
            ),
        ),
    ]
