# Generated by Django 5.1.4 on 2025-04-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_prescriptions_appointment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptions",
            name="appointment_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
