# Generated by Django 5.1.4 on 2025-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_prescriptions_appointment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testbooking",
            name="booking_time",
        ),
        migrations.AlterField(
            model_name="testbooking",
            name="patient",
            field=models.CharField(default="Patient's Email", max_length=100),
        ),
        migrations.AlterField(
            model_name="testbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Sample Collected", "Sample Collected"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testbooking",
            name="test_department",
            field=models.CharField(default="Department email", max_length=100),
        ),
    ]
