# Generated by Django 5.1.4 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_remove_testbooking_booking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthpackagebookings",
            name="branch",
            field=models.CharField(default="Hospital branch", max_length=100),
        ),
        migrations.AlterField(
            model_name="healthpackagebookings",
            name="patient",
            field=models.CharField(default="Patient's Email", max_length=100),
        ),
        migrations.AlterField(
            model_name="healthpackagebookings",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Sample Collected", "Sample Collected"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
