# Generated by Django 5.1.4 on 2025-04-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_healthpackagebookings_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Sample Collected", "Sample Collected"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Completion Notified", "Completion Notified"),
                    ("Cancelled", "Cancelled"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
