# Generated by Django 5.1.4 on 2025-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_testbooking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailability",
            name="emergency_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="emergency_stop_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
