# Generated by Django 5.1.4 on 2025-04-12 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_doctoravailability_emergency_start_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="chat_uploads/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
