# Generated by Django 5.1.4 on 2025-04-12 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_groupmessages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_uploads/"),
        ),
        migrations.AlterField(
            model_name="messages",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="core.users",
            ),
        ),
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("members", models.ManyToManyField(to="core.users")),
            ],
        ),
        migrations.AddField(
            model_name="messages",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.chatgroup",
            ),
        ),
        migrations.DeleteModel(
            name="GroupMessages",
        ),
    ]
