# Generated by Django 5.1.4 on 2025-04-20 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_messages_image_alter_messages_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chat_images/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "department_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.departments",
                        to_field="name",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
