# Generated by Django 5.1.4 on 2025-04-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_groupmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.users",
                to_field="email",
            ),
        ),
    ]
