# Generated by Django 5.1.4 on 2025-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_groupmessage_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="department_group",
            field=models.CharField(max_length=255),
        ),
    ]
