# Generated by Django 5.1.4 on 2025-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthpackagebookings",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
    ]
