# Generated by Django 5.1.4 on 2025-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_healthpackagebookings_amount_delete_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthpackagebookings",
            name="receipt_id",
            field=models.CharField(default="00000000", max_length=10, unique=True),
        ),
    ]
