# Generated by Django 5.1.4 on 2025-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_healthpackagebookings_receipt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthpackagebookings",
            name="receipt_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
