# Generated by Django 5.1.4 on 2025-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_healthpackagebookings_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthpackagebookings",
            name="package_name",
            field=models.CharField(default="Health Package Name", max_length=100),
        ),
    ]
